### ISSUE TITLE
Ubuntu 20.04.5 LTS - Compilation Warnings

### ISSUE THREAD

**Issue by lesouriciergris** [Paul-Tew/lifer#2]
Hello,

Nice program, it compiles and runs but many warnings at compilation.

[trace.txt](https://github.com/Paul-Tew/lifer/files/9617147/trace.txt)

Very good work

Thanks

**Comment by Paul-Tew** [comment]
I tried to warn folks about my inexperience (and hence the warnings at compile time). To be honest at the time I conceived and wrote this program all I wanted was the output for the textual results. I could then confidently present my findings in a court of law and show how each byte corresponded to the MS-SHLLINK document. When people leave digital fragments behind on a hard-drive they can sometimes be an alibi or can also be evidence of a crime ;) Link files are one (small) piece of a larger picture and can sometimes contain a heap of useful information that along with other evidence can assist in conviction or acquittal.
I am working (intermittently) on a new version of this program but in a better (more type-safe) language.
